Watching for file changes with StatReloader
"OPTIONS /graphql/ HTTP/1.1" 200 0
"OPTIONS /graphql/ HTTP/1.1" 200 0
"OPTIONS /graphql/ HTTP/1.1" 200 0
Not Found: /favicon.ico
Not Found: /manifest.json
"GET /favicon.ico HTTP/1.1" 404 2582
"GET /manifest.json HTTP/1.1" 404 2588
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/starwars/schema.py", line 4, in <module>
    from graphene_django.filter import DjangoFilterConnectionField
ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 89, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'starwars.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py).
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/starwars/schema.py", line 4, in <module>
    from graphene_django.filter import DjangoFilterConnectionField
ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 89, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'starwars.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py).
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/starwars/schema.py", line 4, in <module>
    from graphene_django.filter import DjangoFilterConnectionField
ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 89, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'starwars.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py).
"POST /graphql/ HTTP/1.1" 500 122657
"POST /graphql/ HTTP/1.1" 500 122657
"POST /graphql/ HTTP/1.1" 500 122658
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/starwars/schema.py", line 4, in <module>
    from graphene_django.filter import DjangoFilterConnectionField
ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 89, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'starwars.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py).
"POST /graphql/ HTTP/1.1" 500 122657
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/starwars/schema.py", line 4, in <module>
    from graphene_django.filter import DjangoFilterConnectionField
ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 89, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'starwars.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py).
"POST /graphql/ HTTP/1.1" 500 122657
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/starwars/schema.py", line 4, in <module>
    from graphene_django.filter import DjangoFilterConnectionField
ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 89, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'starwars.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py).
"POST /graphql/ HTTP/1.1" 500 122658
Watching for file changes with StatReloader
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/starwars/schema.py", line 4, in <module>
    from graphene_django.filter import DjangoFilterConnectionField
ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 89, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'starwars.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py).
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/starwars/schema.py", line 4, in <module>
    from graphene_django.filter import DjangoFilterConnectionField
ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 89, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'starwars.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py).
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/starwars/schema.py", line 4, in <module>
    from graphene_django.filter import DjangoFilterConnectionField
ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 89, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'starwars.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py).
"POST /graphql/ HTTP/1.1" 500 122657
"POST /graphql/ HTTP/1.1" 500 122657
"POST /graphql/ HTTP/1.1" 500 122658
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/starwars/schema.py", line 4, in <module>
    from graphene_django.filter import DjangoFilterConnectionField
ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 89, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'starwars.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py).
"POST /graphql/ HTTP/1.1" 500 122657
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/starwars/schema.py", line 4, in <module>
    from graphene_django.filter import DjangoFilterConnectionField
ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 89, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'starwars.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py).
"POST /graphql/ HTTP/1.1" 500 122657
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/starwars/schema.py", line 4, in <module>
    from graphene_django.filter import DjangoFilterConnectionField
ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 89, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'starwars.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py).
"POST /graphql/ HTTP/1.1" 500 122658
Not Found: /
"GET / HTTP/1.1" 404 2533
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2584
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
"GET /static/admin/css/base.css HTTP/1.1" 200 21207
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18533
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
Not Found: /
"GET / HTTP/1.1" 404 2533
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/starwars/schema.py", line 4, in <module>
    from graphene_django.filter import DjangoFilterConnectionField
ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 89, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'starwars.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py).
"GET /graphql/ HTTP/1.1" 500 123403
Not Found: /api/starwars/
"GET /api/starwars/ HTTP/1.1" 404 2839
Not Found: /api/graphql/
"GET /api/graphql/ HTTP/1.1" 404 2587
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/starwars/schema.py", line 4, in <module>
    from graphene_django.filter import DjangoFilterConnectionField
ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 89, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'starwars.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py).
"GET /graphql/ HTTP/1.1" 500 123403
Watching for file changes with StatReloader
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/starwars/schema.py", line 4, in <module>
    from graphene_django.filter import DjangoFilterConnectionField
ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 89, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'starwars.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py).
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/starwars/schema.py", line 4, in <module>
    from graphene_django.filter import DjangoFilterConnectionField
ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 89, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'starwars.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py).
Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/starwars/schema.py", line 4, in <module>
    from graphene_django.filter import DjangoFilterConnectionField
ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 97, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/graphene_django/settings.py", line 89, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'starwars.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'DjangoFilterConnectionField' from 'graphene_django.filter' (/usr/local/lib/python3.11/site-packages/graphene_django/filter/__init__.py).
"POST /graphql/ HTTP/1.1" 500 122657
"POST /graphql/ HTTP/1.1" 500 122657
"POST /graphql/ HTTP/1.1" 500 122658
Watching for file changes with StatReloader
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 259
"POST /graphql/ HTTP/1.1" 200 267
"POST /graphql/ HTTP/1.1" 200 265
"POST /graphql/ HTTP/1.1" 200 265
"POST /graphql/ HTTP/1.1" 200 259
"POST /graphql/ HTTP/1.1" 200 267
"POST /graphql/ HTTP/1.1" 200 185
"POST /graphql/ HTTP/1.1" 200 189
"POST /graphql/ HTTP/1.1" 200 188
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 188
"POST /graphql/ HTTP/1.1" 200 185
"POST /graphql/ HTTP/1.1" 200 189
"POST /graphql/ HTTP/1.1" 200 185
Not Found: /manifest.json
"POST /graphql/ HTTP/1.1" 200 188
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 188
"POST /graphql/ HTTP/1.1" 200 185
"POST /graphql/ HTTP/1.1" 200 189
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 188
"POST /graphql/ HTTP/1.1" 200 185
"POST /graphql/ HTTP/1.1" 200 189
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 188
"POST /graphql/ HTTP/1.1" 200 185
"POST /graphql/ HTTP/1.1" 200 189
"POST /graphql/ HTTP/1.1" 200 188
"POST /graphql/ HTTP/1.1" 200 185
"POST /graphql/ HTTP/1.1" 200 189
"POST /graphql/ HTTP/1.1" 200 1527
"POST /graphql/ HTTP/1.1" 200 7104
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 943
"POST /graphql/ HTTP/1.1" 200 44595
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 23370
"GET /graphql HTTP/1.1" 301 0
"GET /graphql/ HTTP/1.1" 200 2611
"GET /static/graphene_django/graphiql.js HTTP/1.1" 200 4037
"GET /static/graphene_django/graphiql.js HTTP/1.1" 200 4037
"POST /graphql/ HTTP/1.1" 200 54449
"POST /graphql/ HTTP/1.1" 200 507
"POST /graphql/ HTTP/1.1" 200 987
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 2695
"POST /graphql/ HTTP/1.1" 200 166
Watching for file changes with StatReloader
"OPTIONS /graphql/ HTTP/1.1" 200 0
"OPTIONS /graphql/ HTTP/1.1" 200 0
"OPTIONS /graphql/ HTTP/1.1" 200 0
Not Found: /manifest.json
Not Found: /favicon.ico
"GET /manifest.json HTTP/1.1" 404 2588
"GET /favicon.ico HTTP/1.1" 404 2582
"POST /graphql/ HTTP/1.1" 200 943
"POST /graphql/ HTTP/1.1" 200 7104
"POST /graphql/ HTTP/1.1" 200 1527
"POST /graphql/ HTTP/1.1" 200 44595
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 23370
Watching for file changes with StatReloader
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 943
"POST /graphql/ HTTP/1.1" 200 7104
"POST /graphql/ HTTP/1.1" 200 1527
"POST /graphql/ HTTP/1.1" 200 23370
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 44595
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
"POST /graphql/ HTTP/1.1" 400 125
"POST /graphql/ HTTP/1.1" 400 127
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
"POST /graphql/ HTTP/1.1" 400 127
"POST /graphql/ HTTP/1.1" 400 125
"POST /graphql/ HTTP/1.1" 400 127
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 125
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Watching for file changes with StatReloader
Not Found: /main.f85aaf012cd8b476f9a8.hot-update.json
"GET /main.f85aaf012cd8b476f9a8.hot-update.json HTTP/1.1" 404 2672
Bad Request: /graphql/
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
"POST /graphql/ HTTP/1.1" 400 127
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 125
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 125
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
"POST /graphql/ HTTP/1.1" 400 127
"POST /graphql/ HTTP/1.1" 400 125
"GET /graphql/ HTTP/1.1" 200 2611
"GET /static/graphene_django/graphiql.js HTTP/1.1" 200 4037
"POST /graphql/ HTTP/1.1" 200 54449
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2584
"POST /graphql/ HTTP/1.1" 200 166
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 104
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 126
Watching for file changes with StatReloader
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
"POST /graphql/ HTTP/1.1" 400 127
"POST /graphql/ HTTP/1.1" 400 125
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 125
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 125
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 125
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Watching for file changes with StatReloader
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
Bad Request: /graphql/
Bad Request: /graphql/
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
"POST /graphql/ HTTP/1.1" 400 127
"POST /graphql/ HTTP/1.1" 400 125
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 125
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 126
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 126
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 126
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 126
"POST /graphql/ HTTP/1.1" 200 25416
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 125
Bad Request: /graphql/
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 125
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 125
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 125
Watching for file changes with StatReloader
Not Found: /main.cbb9ab9b7aa40d1ba5db.hot-update.json
"GET /main.cbb9ab9b7aa40d1ba5db.hot-update.json HTTP/1.1" 404 2672
"OPTIONS /graphql/ HTTP/1.1" 200 0
"OPTIONS /graphql/ HTTP/1.1" 200 0
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 23370
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 23370
"POST /graphql/ HTTP/1.1" 200 208
"POST /graphql/ HTTP/1.1" 200 72660
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 23370
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 23370
Watching for file changes with StatReloader
Not Found: /main.8d67d957ec485e97d517.hot-update.json
"GET /main.8d67d957ec485e97d517.hot-update.json HTTP/1.1" 404 2672
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 23210
"POST /graphql/ HTTP/1.1" 200 40796
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 23210
"POST /graphql/ HTTP/1.1" 200 40796
"POST /graphql/ HTTP/1.1" 200 36977
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
"POST /graphql/ HTTP/1.1" 200 23210
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
"POST /graphql/ HTTP/1.1" 200 36977
"POST /graphql/ HTTP/1.1" 200 48053
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
"POST /graphql/ HTTP/1.1" 200 36977
"POST /graphql/ HTTP/1.1" 200 48053
"POST /graphql/ HTTP/1.1" 200 36977
"POST /graphql/ HTTP/1.1" 200 23210
"POST /graphql/ HTTP/1.1" 200 36977
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
Bad Request: /graphql/
"POST /graphql/ HTTP/1.1" 400 127
"POST /graphql/ HTTP/1.1" 200 36977
"POST /graphql/ HTTP/1.1" 200 48053
Watching for file changes with StatReloader
Not Found: /main.bb090528149024027fb3.hot-update.json
"GET /main.bb090528149024027fb3.hot-update.json HTTP/1.1" 404 2672
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 25416
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 23370
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 23370
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 72660
Watching for file changes with StatReloader
Not Found: /main.40992c8d01584dc42a84.hot-update.json
"GET /main.40992c8d01584dc42a84.hot-update.json HTTP/1.1" 404 2672
"POST /graphql/ HTTP/1.1" 200 37138
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
Watching for file changes with StatReloader
Not Found: /main.0db8d97f5c5fa20483df.hot-update.json
"GET /main.0db8d97f5c5fa20483df.hot-update.json HTTP/1.1" 404 2672
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 23370
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 72660
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
Watching for file changes with StatReloader
Not Found: /main.6e6682e25d13e65e3305.hot-update.json
"GET /main.6e6682e25d13e65e3305.hot-update.json HTTP/1.1" 404 2672
"POST /graphql/ HTTP/1.1" 200 37138
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 40956
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
Watching for file changes with StatReloader
Not Found: /main.9bec43ed4d241e266089.hot-update.json
"GET /main.9bec43ed4d241e266089.hot-update.json HTTP/1.1" 404 2672
"POST /graphql/ HTTP/1.1" 200 37138
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 40956
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
Watching for file changes with StatReloader
"POST /graphql/ HTTP/1.1" 200 25416
"POST /graphql/ HTTP/1.1" 200 25416
"POST /graphql/ HTTP/1.1" 200 25416
"POST /graphql/ HTTP/1.1" 200 25416
Not Found: /manifest.json
"POST /graphql/ HTTP/1.1" 200 37138
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 40956
Watching for file changes with StatReloader
Not Found: /main.c8b1127e5e702db0dc5b.hot-update.json
"GET /main.c8b1127e5e702db0dc5b.hot-update.json HTTP/1.1" 404 2672
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
Watching for file changes with StatReloader
Not Found: /main.9dc6ff2bf00f3a020612.hot-update.json
"GET /main.9dc6ff2bf00f3a020612.hot-update.json HTTP/1.1" 404 2672
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 23370
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
Watching for file changes with StatReloader
Not Found: /main.7230d00b7ced148fdc40.hot-update.json
"GET /main.7230d00b7ced148fdc40.hot-update.json HTTP/1.1" 404 2672
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 23370
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
Watching for file changes with StatReloader
Not Found: /main.aef3b27c04d03c9d86e2.hot-update.json
"GET /main.aef3b27c04d03c9d86e2.hot-update.json HTTP/1.1" 404 2672
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 23370
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 72660
Watching for file changes with StatReloader
Not Found: /main.40992c8d01584dc42a84.hot-update.json
"GET /main.40992c8d01584dc42a84.hot-update.json HTTP/1.1" 404 2672
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 72660
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 72660
"POST /graphql/ HTTP/1.1" 200 23370
"POST /graphql/ HTTP/1.1" 200 351
"POST /graphql/ HTTP/1.1" 200 73020
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 73020
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
Watching for file changes with StatReloader
"POST /graphql/ HTTP/1.1" 200 37138
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 40956
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 73020
"POST /graphql/ HTTP/1.1" 200 23370
Watching for file changes with StatReloader
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 73020
"POST /graphql/ HTTP/1.1" 200 23370
Watching for file changes with StatReloader
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 73020
"POST /graphql/ HTTP/1.1" 200 23370
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 8970
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 73020
Watching for file changes with StatReloader
Not Found: /main.232c56d640f9f74afad7.hot-update.json
"GET /main.232c56d640f9f74afad7.hot-update.json HTTP/1.1" 404 2672
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
Not Found: /main.232c56d640f9f74afad7.hot-update.json
"GET /main.232c56d640f9f74afad7.hot-update.json HTTP/1.1" 404 2672
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 73020
"POST /graphql/ HTTP/1.1" 200 73020
"POST /graphql/ HTTP/1.1" 200 48214
Watching for file changes with StatReloader
"POST /graphql/ HTTP/1.1" 200 23370
"POST /graphql/ HTTP/1.1" 200 23370
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 73020
"POST /graphql/ HTTP/1.1" 200 23370
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 23370
Watching for file changes with StatReloader
Not Found: /main.f338d6921a95ca018f63.hot-update.json
"GET /main.f338d6921a95ca018f63.hot-update.json HTTP/1.1" 404 2672
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 73020
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 23370
"POST /graphql/ HTTP/1.1" 200 23370
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 8970
"POST /graphql/ HTTP/1.1" 200 40956
Watching for file changes with StatReloader
Not Found: /main.41c918d02ad4bc129b83.hot-update.json
"GET /main.41c918d02ad4bc129b83.hot-update.json HTTP/1.1" 404 2672
Not Found: /manifest.json
"POST /graphql/ HTTP/1.1" 200 37138
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 73020
"POST /graphql/ HTTP/1.1" 200 23370
Not Found: /main.41c918d02ad4bc129b83.hot-update.json
"GET /main.41c918d02ad4bc129b83.hot-update.json HTTP/1.1" 404 2672
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 23370
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 8970
"POST /graphql/ HTTP/1.1" 200 40956
Watching for file changes with StatReloader
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
Watching for file changes with StatReloader
Not Found: /main.446f77c5b4585042d364.hot-update.json
"GET /main.446f77c5b4585042d364.hot-update.json HTTP/1.1" 404 2672
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 8970
Not Found: /main.90ccf719d053bbd47142.hot-update.json
"GET /main.90ccf719d053bbd47142.hot-update.json HTTP/1.1" 404 2672
"POST /graphql/ HTTP/1.1" 200 40956
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 73020
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 8970
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 73020
"POST /graphql/ HTTP/1.1" 200 23370
Watching for file changes with StatReloader
Not Found: /main.bcd7b0e3bff7b60c1aa6.hot-update.json
"GET /main.bcd7b0e3bff7b60c1aa6.hot-update.json HTTP/1.1" 404 2672
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
Watching for file changes with StatReloader
Not Found: /main.bcd7b0e3bff7b60c1aa6.hot-update.json
"GET /main.bcd7b0e3bff7b60c1aa6.hot-update.json HTTP/1.1" 404 2672
Not Found: /main.ebbb72c405f7340ed85d.hot-update.json
"GET /main.ebbb72c405f7340ed85d.hot-update.json HTTP/1.1" 404 2672
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 23370
Not Found: /manifest.json
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 8970
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 73020
"POST /graphql/ HTTP/1.1" 200 73020
Not Found: /manifest.json
"POST /graphql/ HTTP/1.1" 200 777
"GET /manifest.json HTTP/1.1" 404 2588
"POST /graphql/ HTTP/1.1" 200 40956
"POST /graphql/ HTTP/1.1" 200 73020
"POST /graphql/ HTTP/1.1" 200 37138
"POST /graphql/ HTTP/1.1" 200 48214
"POST /graphql/ HTTP/1.1" 200 23370
Watching for file changes with StatReloader
"GET /docs/ HTTP/1.1" 200 1604
"GET /static/drf-yasg/style.css HTTP/1.1" 200 1047
"GET /static/drf-yasg/insQ.min.js HTTP/1.1" 200 2093
"GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 200 14964
"GET /static/drf-yasg/immutable.min.js HTTP/1.1" 200 56904
"GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 200 145206
"GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 200 322863
"GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 200 1046583
"GET /docs/?format=openapi HTTP/1.1" 200 13681
"GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
"GET /api/starwars/characters/?page=1&page_size=20 HTTP/1.1" 200 9926
"GET /api/starwars/planets/ HTTP/1.1" 200 11629
"GET /redoc/ HTTP/1.1" 200 930
"GET /static/drf-yasg/style.css HTTP/1.1" 304 0
"GET /static/drf-yasg/insQ.min.js HTTP/1.1" 304 0
"GET /static/drf-yasg/redoc-init.js HTTP/1.1" 200 2566
"GET /static/drf-yasg/redoc/redoc.min.js HTTP/1.1" 200 1042511
"GET /redoc/?format=openapi HTTP/1.1" 200 13681
"GET /static/drf-yasg/redoc/redoc-logo.png HTTP/1.1" 200 4969
